"""Rename products tabl name to product

Revision ID: 81e72e335c7e
Revises: e9f899b0be74
Create Date: 2023-04-25 19:00:04.189458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e72e335c7e'
down_revision = 'e9f899b0be74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category', sa.String(
                        length=500), nullable=True),
                    sa.Column('sku', sa.String(length=500), nullable=True),
                    sa.Column('product', sa.String(length=500), nullable=True),
                    sa.Column('description', sa.String(
                        length=5000), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('breadcrumb', sa.String(
                        length=500), nullable=True),
                    sa.Column('product_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('money_back', sa.Boolean(), nullable=True),
                    sa.Column('rating', sa.Float(), nullable=True),
                    sa.Column('total_reviews', sa.Integer(), nullable=True),
                    sa.Column('tags', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('category', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('sku', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('product', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(length=5000),
                              autoincrement=False, nullable=True),
                    sa.Column('price', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=True),
                    sa.Column('breadcrumb', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('product_url', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('money_back', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=True),
                    sa.Column('total_reviews', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('tags', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='products_pkey')
                    )
    op.drop_table('product')
    # ### end Alembic commands ###
