"""empty message

Revision ID: bb8e2d842586
Revises: 971f2fc19d4a
Create Date: 2023-04-19 16:01:43.275789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb8e2d842586'
down_revision = '971f2fc19d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('bot_response', sa.Text(), nullable=True),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('initial_response', sa.Text(), nullable=True),
    sa.Column('level1', sa.Text(), nullable=True),
    sa.Column('level2', sa.Text(), nullable=True),
    sa.Column('level3', sa.Text(), nullable=True),
    sa.Column('level4', sa.Text(), nullable=True),
    sa.Column('response_accepted', sa.Boolean(), nullable=True),
    sa.Column('response_time', sa.SmallInteger(), nullable=True),
    sa.Column('discord_id', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chatbot_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_input', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bot_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('initial_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('initial_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('response_time', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('discord_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chatbot_data_pkey')
    )
    op.drop_table('chatbot_datas')
    # ### end Alembic commands ###
