"""Initial migration.

Revision ID: e9f899b0be74
Revises: 
Create Date: 2023-04-21 14:57:28.263959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f899b0be74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('bot_response', sa.Text(), nullable=True),
    sa.Column('initial_prompt', sa.Text(), nullable=True),
    sa.Column('initial_response', sa.Text(), nullable=True),
    sa.Column('level1', sa.Text(), nullable=True),
    sa.Column('level2', sa.Text(), nullable=True),
    sa.Column('level3', sa.Text(), nullable=True),
    sa.Column('level4', sa.Text(), nullable=True),
    sa.Column('response_accepted', sa.Boolean(), nullable=True),
    sa.Column('response_time', sa.SmallInteger(), nullable=True),
    sa.Column('discord_id', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('sku', sa.String(length=500), nullable=True),
    sa.Column('product', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('breadcrumb', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('money_back', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('chatbot_datas')
    # ### end Alembic commands ###
