version: '3'

services:
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash ./start.sh
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0"
          memory: "0.5GB"